### ISSUE TITLE
mrouted-3.9.7_Multicast_Forward_Issue

### ISSUE THREAD

**Issue by baskar1975** [troglobit/mrouted#33] opened 2020-02-28 15:48 UTC
Hi,

We integrating the DVMRP is our protocol and we found the muticast is not forwarding from one VLAN to another VLAN.

The host is connected with switch through VLAN1 and VLAN2 is connected with another switch with same configuration.

" Host1-VLAN1->VLAN2----VLAN2->VLAN3-Host2 "

The multicast(239.0.0.100) UDP packet is received in the dvmrp flow,but it is not appearing in VLAN2.

For your information PIM-DIM is working with our environment and we are using BCM SDK.

Same way we are integrating the DVMRP ,but the multicast message is not flooding.
Please hep us to identify the issue ,because it is very urgent requirement.

**Comment by troglobit** [comment] 2020-02-28 15:57
Since you mention PIM-DM working (curious what implementation you're using :), I'm assuming you know how to set up multicast senders and receivers, as well as know about setting the TTL correct on the senders.

Please try the latest version, [v3.9.8](https://github.com/troglobit/mrouted/releases/tag/3.9.8).  It has at least one fix that might be relevant to your setup.

If v3.9.8 doesn't work, you could try the pre-release of the next major release, [v4.0-rc1](https://github.com/troglobit/mrouted/releases/tag/4.0-rc1).  It still requires a lot of testing before the GA release, but also has a lot of stability fixes and modernization of the code base.

**Comment by baskar1975** [comment] 2020-02-29 10:53
Hi,

Thank you for the  valuable information,but the customer requested with 3.9.7 version.

We setting TTL =10 sec in sender and packet is receiving in the source VLAN input port,but not forwarding to the another VLAN port in the switch.
The IGMP snooping is disabled ,but in the starting itself the multicast is not flooding.
Please help us to identify the issue.

**Comment by troglobit** [comment] 2020-02-29 12:29
First of all, talk to your customer.  The 3.9.7 release is over 5 years old and has bugs.  There are no compatibility issues between that and 3.9.8, only bug fixes which may help with your particular case. 

I just tested 3.9.7 in [CORE](https://github.com/coreemu/core), and it works fine in a similar setup.  Notice I've not started the receiver on H2, and the first router which is receiving multicast from H1 is flooding it towards the second router:

![core-two-routers](https://user-images.githubusercontent.com/183517/75607367-ada5cb80-5af6-11ea-83c5-3268bf679a0c.png)

Usually when there is a problem with flooding it's because the routers haven't peered, i.e. they cannot hear each other.  Have you made sure to set the MULTICAST flag on the interfaces on which mrouted runs?  Does each of the routers receive DVMRP control traffic from its neighbor?

**Comment by troglobit** [comment] 2020-03-02 19:10
How are things progressing?  If there are no apparent bugs with mrouted, I'd like to close this issue.

**Comment by baskar1975** [comment] 2020-03-03 15:12
Hi,
Currently we are integrated “mrouted - 3.9.7” with our target platform and started debugging in switch.
Any way parallelly our team also tying to integrate with latest version “mrouted-4.0-rc1”, but it will take little time.
So, we are continuing with “mrouted - 3.9.7” for debugging and checked the dvmrp probe message are interchanging along the networks as like 10.0.1.1 ->10.0.0.1 <-> 10.0.0.2<- 10.0.2.1.

The H1(10.0.1.10) traffic is received up to 10.0.1.1, but is not forwarding to 10.0.0.1.

Is it possible to share your network and dvmrp CLI configuration for our verification?

**Comment by troglobit** [comment] 2020-03-03 16:11
There is nothing in particular to the setup I use for testing.  Simple IPv4 base networking and mrouted running with the default configuration, i.e. no .conf file at all.  For the above case I didn't even set up RIP for unicast.

**Comment by baskar1975** [comment] 2020-03-05 14:52
Hi,
 As per your suggestion the MULTICAST flag is set for each interface and the peering also checked. But the flood is not happening in R1 router source to R2 router in the client side.

Please find the R1 router and R2 router log attached for your verification and check it please give your suggestion.

[R1_source.log](https://github.com/troglobit/mrouted/files/4293532/R1_source.log)
[R2_client.log](https://github.com/troglobit/mrouted/files/4293534/R2_client.log)

**Comment by troglobit** [comment] 2020-03-05 16:10
From the log you seem to use TTL scoping, the TTL threshold is set to 64 for two interfaces.  Is this intended?   For initial flooding, and multicast routing, to work the incoming stream must have a TTL >64 to be forwarded to those two interfaces.

(You also have rate limiting enabled for these interfaces.)

```
Virtual Interface Table
Vif  Name  Local-Address                               M  Thr  Rate   Flags
 0 eth1.1  10.0.50.1       subnet: 10.0.50/24          1   1      0   disabled
                      Nbr bitmaps: 0x0000000000000000

 1 eth1.2  10.0.1.1        subnet: 10.0.1/24           1  64    500   querier
                     IGMP querier: 10.0.1.1           (this system)
                      Nbr bitmaps: 0x0000000000000000

 2 eth1.3  10.0.0.1        subnet: 10.0.0/24           1  64    500   querier
                     IGMP querier: 10.0.0.1           (this system)
                      Nbr bitmaps: 0x0000000000000000
```

**Comment by baskar1975** [comment] 2020-03-06 16:13
No, We are not setting intentionally the TTL value to 64 ,but when the mrouted run time the value is processing.
Is it any other way to debug the TTL value modification in the run time.

**Comment by troglobit** [comment] 2020-03-06 17:22
I see, well then you might have run into a very old bug ... make sure to check the system after initial bootstrap using either the SIGUSR1/SIGUSR2 interface or `mrouted -r`.   If that doesn't help, you could increase the TTL of your sender(s) to see if mrouted then starts flooding.

I'm sort of running out of ideas, and it's really hard for me to help you since you're not running on standard HW.  Also, I understand your pain but I cannot justify spending too much more time helping you out for free when I have a lot of other things I'd rather spend my free time on ... sorry.

**Comment by baskar1975** [comment] 2020-03-09 15:24
Hi,

Thank you very much for patient and support and it is really very helpful us to debug.
Yes, same platform(BCM) the PIM-Dim is working and the TTL value is set to default one and there is no issue.

As per your suggestion we increased the TTL value in the sender side and the flooding is happening in both the routers “R1” and “R2”.

The TTL value is automatically changed to 10 as seen below in the below log, but  in the log we found one error at the time of joint report MRT_ADD_MFC.



12:52:55.741 Aging forwarding cache entries
12:52:55.741 SENT neighbor probe     from 10.0.1.1        to 224.0.0.4
12:52:55.741 SENT neighbor probe     from 10.0.0.1        to 224.0.0.4
12:52:58.933 RECV neighbor probe     from 10.0.0.2        to 224.0.0.4
12:52:58.933 sree__ accept_probe in route.c source= 10.0.0.2, Destination= 224.0.0.4
12:52:58.933 Checking probe from 10.0.0.2 (3.255) on vif 2
12:52:58.933 sreeeeee------------ Router=10.0.0.1 in_router_list=0 Level=1048323
12:53:00.938 Aging forwarding cache entries
12:53:03.749 warning - Kernel entry already exists for (10.0.2.10 225.1.2.3)
12:53:03.749 SREE**********TTL* mc.mfcc_ttls[0]=10 numvifs=3
12:53:03.749 SREE**********TTL* mc.mfcc_ttls[1]=10 numvifs=3
12:53:03.749 SREE**********TTL* mc.mfcc_ttls[2]=10 numvifs=3
12:53:03.749 SREE ======= mc.mfcc_paren=32 socket=3 setsockopt fd=-1 IPPROTO_IP=(null) MRT_ADD_MFC=204 Adding kernel MFC entry for source=10.0.2.10 and group=225.1.2.3
12:53:05.753 Aging forwarding cache entries
12:53:05.753 SENT neighbor probe     from 10.0.1.1        to 224.0.0.4
12:53:05.753 SENT neighbor probe     from 10.0.0.1        to 224.0.0.4
12:53:08.971 RECV neighbor probe     from 10.0.0.2        to 224.0.0.4
12:53:08.971 sree__ accept_probe in route.c source= 10.0.0.2, Destination= 224.0.0.4
12:53:08.971 Checking probe from 10.0.0.2 (3.255) on vif 2
12:53:08.971 sreeeeee------------ Router=10.0.0.1 in_router_list=0 Level=1048323
12:53:10.976 Aging forwarding cache entries
12:53:10.976 update 1 starting at 2 of 2
12:53:13.767 warning - Kernel entry already exists for (10.0.2.10 225.1.2.3)
12:53:13.767 SREE**********TTL* mc.mfcc_ttls[0]=10 numvifs=3
12:53:13.767 SREE**********TTL* mc.mfcc_ttls[1]=10 numvifs=3
12:53:13.767 SREE**********TTL* mc.mfcc_ttls[2]=10 numvifs=3
12:53:13.768 SREE ======= mc.mfcc_paren=32 socket=3 setsockopt fd=-1 IPPROTO_IP=(null) MRT_ADD_MFC=204 Adding kernel MFC entry for source=10.0.2.10 and group=225.1.2.3
12:53:15.772 Aging forwarding cache entries

**Comment by troglobit** [comment] 2020-03-09 18:10
OK, so at least mrouted works if you increase the sender's TTL.  My suspicion is that there is some sort of bug in the probing of interfaces and setting up their default values.  This code is in `config_vifs_from_kernel()` and `zero_vifs()`, so I'd focus my attention on that part of the code if I were you. There could be some endian problem, for instance.

Regarding the latest log you sent, I honestly cannot read it and identify which message goes with what piece of code?  You must have added a lot extra traces when debugging, because I don't recognize much.  However, the "warning - Kernel entry already exists" is nothing to worry about.  The severity of that message should probably be lowered to LOG_INFO or something.

Also, a heads-up; the "TTL" you see in context of `mc.mfcc-ttls` etc. is **not at all** related to the TTL threshold of interfaces or incoming multicast streams.  It is the legacy API to setting outbound interfaces for a multcast route.  See the corresponding code in the latest mrouted (master branch) for more helpful debug message: 

   https://github.com/troglobit/mrouted/blob/master/src/kern.c#L235

**Comment by baskar1975** [comment] 2020-03-12 16:16
The flooding is happing up to the end point of the R2 router, but not receiving in the client H2(10.0.2.10). 

Because we are getting error at the function “void k_add_rg(uint32_t origin, struct gtable *g)” in the below line.
“mc.mfcc_parent = g->gt_route ? g->gt_route->rt_parent : NO_VIF;”
The interface number is updating wrongly “mc.mfcc_parent=32”, so the set option returning error at 
“if (setsockopt(igmp_socket, IPPROTO_IP, MRT_ADD_MFC, (char *)&mc, sizeof(mc)) < 0)
Error Return as:
“setsockopt MRT_ADD_MFC   10.0.2.10   225.1.2.3”

Please find help us to identify the interface number issue.

**Comment by troglobit** [comment] 2020-03-13 07:09
Well, that's by design (and RFC).  Flooding should only take place to all routers, not to all end devices.  For each LAN the clients (and the router) rely on IGMP to control the distribution of multicast.

**Comment by baskar1975** [comment] 2020-03-16 14:08
We are getting error at the function “void k_add_rg(uint32_t origin, struct gtable *g)” in the below line.

“mc.mfcc_parent = g->gt_route ? g->gt_route->rt_parent : NO_VIF;”

The interface number is updating wrongly “mc.mfcc_parent=32”, so the set option returning error at

“if (setsockopt(igmp_socket, IPPROTO_IP, MRT_ADD_MFC, (char *)&mc, sizeof(mc)) < 0)

**Comment by troglobit** [comment] 2020-03-16 17:17
The `mc.mfcc_parent` gets assigned `NO_VIF` because there is no reverse path for the route.  This is usually because `determine_route()` failed earlier.

I'm not sure why that happens to you, but like I said early on, v3.9.7 is really old and I do not have the ability to support such old releases.  In v3.9.8 we added `--startup-delay` which helped some users with NICs that took a while to come up at boot.  With a variable startup delay of mrouted they could tweak the time before NIC were queried for their IP addresses etc.  (I'm assuming you have the unicast paths set up between all devices in the network.)

**Comment by baskar1975** [comment] 2020-03-21 07:17
There is no major difference between v3.9.7 to 3.9.8 and there is no problem in startup delay.

But there is a bug in  “mc.mfcc_parent = g->gt_route ? g->gt_route->rt_parent : NO_VIF;” and it returning wrong interface number.

Input and output interface driving is clearly implemented in the PIM source flow ,but not implemented in the mrouted source code flow.
The source for PIM and mrouted has difference in the interface driving method,so we are struggling to the bring the changes from PIM to mrouted.

**Comment by troglobit** [comment] 2020-03-21 08:50
Is there any way you can give me a setup with regular PCs where you can replicate the problem you have?  Because 22 days in, I'm really struggling to understand your issue from my side.

PIM and DVMRP are very different protocols, and even if they share a lot of the code base, I'm not sure that porting anything from pimd to mrouted is the right thing to do.  

If you could help me replicate your problem on my side we could look at [the RFC](https://tools.ietf.org/html/rfc1075), and the [draft rfc](https://tools.ietf.org/html/draft-ietf-idmr-dvmrp-v3-11) that mrouted implements, to nail down the issue.  Because I'm not sure we're getting anywhere by this continued guess-work from both our sides at the momen.

**Comment by baskar1975** [comment] 2020-04-01 05:24
Hi, 
Sorry for the delay here in india has curfew is on going .
I need the following clarification for routing identification in flow:
                           	 SWITCH-1	                       SWITCH-2
    " Host1----->VLAN1->VLAN1.1--------------VLAN2.1->VLAN2------>Host2 "
     
Host1  ->  Source  (It is updated in local routing table in SWITCH-1 ).
Host2 -> Client  (It is updated in local routing table in SWITCH-2).
VLAN1.1 and VLAN2.1 is connected through common vlan interface.

The multicast message is transfers from “Host1” to “SWITCH-2”, then the “DVMRP” in “SWITCH-2” side determine the route path using the following function and the route determine is failing.
“struct rtentry *determine_route(uint32_t src)”

Because of this kernel MRT_ADD_MFC updating is getting failed and Host2 interface path information also getting wrong.
Please clarify this issue.

**Comment by troglobit** [comment] 2020-04-01 08:08
Hi, it seems we do not have a full two-way communication going on here, between me and you. Could you please re-read my previous reply first and try to understand my situation?

I'm sorry, but I cannot be expected to continue to provide free support in your work on this detailed level. It takes too much of my time to try and understand; what you mean, how you are testing, the expected result, and all the possible porting problems you probably have with the device you're trying to run mrouted on.  Also, as you can see from the code, I'm not the original author, so for every case and problem you present I have to spend at least 1-2 hours of unpaid free time to give you an answer.

For me it's a simple equation, unless you provide me with help to reproduce your problem on regular PCs, e.g. using [CORE](https://github.com/coreemu/core), then I'm forced to close this issue.

**Comment by baskar1975** [comment] 2020-04-01 10:02
Yes we are also tested with single switch with different vlan is working.

But with the different vlan with two switch i explained previously is not working.

The path table updation function functions has bug in the release.

Function Name: "void add_table_entry(uint32_t origin, uint32_t mcastgrp)"
“struct rtentry *determine_route(uint32_t src)”.

where it will find the nearer source node path for the "origin".

Please answer only this question it's more enough to fix the bug.

Any thanks to you, my job is questionable in the company.

I am really sorry your not able understand this issue, the RFC is not issue the way of implemented to find the route path logic is the bug in the code.

**Comment by troglobit** [comment] 2020-04-01 17:06
Not really sure how to respond to this ... 

16 days ago I pointed out `determine_route()` to you as a possible cause for why `mc.mfcc_parent` gets assigned `NO_VIF` and now you claim there's a bug without specifying further.  You also say "Please answer only this question..." but I see no question in your last message? I'm really really trying to understand you, but I'm failing hard :disappointed: 

All I'm asking for is help to reproduce this problem it in an environment I have access to -- so I can attach a debugger to it and apply logic, is that too much to ask?

Here's what I've gathered so far: you have some sort of Broadcom based switch that you run as a router using VLAN interfaces.  You have not described how the switch is set up (do you use Linux switchdev and DSA support to get real interfaces, or some Broadcom proprietary handling?), you have not described how you set up those VLANs.  You have not described, in detail, your IP address plan, only given me fragments of information.  Since you haven't explained the basics I don't know if you disabled Linux `rp_filter` and such things.

*One* of my setups when testing mrouted is this (using IP addresses from this bug report):

```

    .----.  10.0.1.0/24  .----.  10.0.0.0/24  .----.  10.0.2.0/24  .----.                	 	 
    | H1 |---------------| R1 |---------------| R2 |---------------| H2 |
    '----'.10          .1'----'.1           .2'----'.1          .10'----'

 mcjoin -s -t 3        mrouted -n            mrouted -n             mcjoin
```
- I use my own program mcjoin to send multicast data from H1, with a TTL of 3,
  to multicast group 225.1.2.3
- I run (the latest version of) mrouted with the `-n` so it runs in the foreground.
  Sometimes with `-l debug -d all` to see debug messages from all subsystems
- I run mcjoin (`-j` is default) on H2 to join group 225.1.2.3

I tried this setup also with the old v3.9.7 release, only slightly different command line options to mrouted.  As I reported, I had no problems, at all.

Here is where you've failed to *help me* in reproducing the problem.  For instance, you could have told me you use switchdev, with all physical switch ports are available in Linux, and that you place all these ports in the Linux bridge, enabling VLAN filtering, adding two VLAN interfaces on top of the bridge, like this:

```
      br0.1    br0.2                br0.1    br0.2   
           \  /                          \  /        
         .--br0---.                    .--br0---.    
        /  /   \   \                  /  /   \   \   
    eth0 eth1  eth2 eth3 -------- eth0 eth1  eth2 eth3
     1U   1U    2U   2U            1U   1U    2U   2U

          Switch 1                      Switch 2
```

Then I could have set up something similar and tested mrouted running on br0.1 and br0.2 on each (emulated) switch.  But as things stand I have nothing to go on, except you persisting in there is a bug and that I should help you answer or clarify something which you then also fail to specify. Do you want me to explain the code paths, what?!  

> Any way thanks to you, my job is questionable in the company.

Well, I've really tried to help you, and now you're seriously blaming me for your status within the company you're working at?  As an open source maintainer, I'm not obliged to provide anyone with free support, that's not how it works. Guilt-tripping me into feeling sorry for you will not change any of that.

**Comment by troglobit** [comment] 2020-06-09 20:11
More than 2 months without any activity.  Closing.  New v4.0 release will be available shortly.

**Closed by troglobit** 2020-06-09 20:11 UTC
