### ISSUE TITLE
Segmentation fault when running with debug all in foureground and closing another mrouted instance

### ISSUE THREAD

**Issue by jotr** [troglobit/mrouted#50] opened 2021-03-03 13:49 UTC
I'm running a setup identical to the one described in this blog post: https://troglobit.com/2016/07/05/multicast-routing-with-pim-sm-over-gre/ Instead of _pimd_ I am running _mrouted_ though.

_mrouted_ is running in the foreground in each of the routers R1 and R2 with the following command line parameters:

`> mrouted -n -l debug -d all`

If I issue Ctrl+C to stop one of the two instances the other one will also terminate with a segmentation fault. This appears to happen reliably on my machines regardless of which side i terminate. If I select any other subystems, or even list all of them individually, there is no crash.

My version of _mrouted_ is 4.2 and I'm running Debian 10.

Cheers from a fellow MDH alumnus (DTV96).

**Comment by troglobit** [comment] 2021-03-04 07:08
Hi, always happy to see people using good 'ol mrouted! :-)

I cannot replicate your segfault, tried it out in CORE on my Linux Mint install, so not exactly the same as you.  I did however catch the following on the neighboring router:

```
07:53:59.703 RECV v3 member report   from 10.10.0.2       to 224.0.0.22
07:53:59.703 IGMP v3 report, 32 bytes, from 10.10.0.2 to 224.0.0.22 with 3 group records.
07:53:59.703 Ignoring IGMP LEAVE/BLOCK for `�v��U on (null), group not found.
07:53:59.703 Ignoring IGMP LEAVE/BLOCK for `�v��U on (null), group not found.
07:53:59.703 Ignoring IGMP LEAVE/BLOCK for `�v��U on (null), group not found.
07:54:00.075 RECV v3 member report   from 10.10.0.2       to 224.0.0.22
07:54:00.075 IGMP v3 report, 32 bytes, from 10.10.0.2 to 224.0.0.22 with 3 group records.
07:54:00.075 Ignoring IGMP LEAVE/BLOCK for `�v��U on (null), group not found.
07:54:00.075 Ignoring IGMP LEAVE/BLOCK for `�v��U on (null), group not found.
07:54:00.075 Ignoring IGMP LEAVE/BLOCK for `�v��U on (null), group not found.
07:54:00.075 SENT neighbor probe     from 10.10.0.1       to 224.0.0.4
```

Maybe you can try following patch to see if it helps?

```patch
diff --git a/src/vif.c b/src/vif.c
index 6246b23..e20ced3 100644
--- a/src/vif.c
+++ b/src/vif.c
@@ -1113,7 +1113,7 @@ void accept_leave_message(int ifi, uint32_t src, uint32_t dst, uint32_t group)
      * older version compat, RFC3376.
      */
     IF_DEBUG(DEBUG_IGMP)
-       logit(LOG_DEBUG, 0, "Ignoring IGMP LEAVE/BLOCK for %s on %s, group not found.");
+       logit(LOG_DEBUG, 0, "Ignoring IGMP LEAVE/BLOCK for %s on %s, group not found.", s3, s1);
 }
 ```

All the best
dat95jnn

**Comment by troglobit** [comment] 2021-03-05 17:22
Any luck?

**Comment by jotr** [comment] 2021-03-08 16:38
Hi, sorry for the delay.

I have now tested with mrouted built from source, with and without your patch, but I have been unable to repeat the problem. What's worse, when I reinstalled from your Debian repo I could not repeat the problem using that version either. Whatever it was it is no longer occuring in my system. Frustrating.

**Comment by troglobit** [comment] 2021-03-08 17:04
No problem, I'd wager this was the root cause anyway.  The bug would be executed while processing an IGMP Leave (IGMP v2), or corresponding IGMP v3 membership record type, report.   So likely only the elected IGMP querier would see this, and then only when `-l debug `-d igmp` is active.

I propose we close this and you open new bug report if you run into the same/similar issue again.

**Comment by jotr** [comment] 2021-03-08 17:10
Sounds good. Thanks for the help.

**Comment by troglobit** [comment] 2021-03-08 17:21
Any time 😃👍

**Closed** 2021-03-08 17:21 UTC
